---
# tasks file for jenkins
- block: # Install Jenkins to AmazonLinux1

  - name: Add official Jenkins repo for CentOS
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install Jenkins
    yum: update_cache=yes name=jenkins state=present

  - name: Start and enable Jenkins during boot
    service: name=jenkins state=started enabled=yes

# Create directory if not exists
  - name: Create initialization scripts directory
    file: 
      path: '{{ jenkins_home }}/init.groovy.d'
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0775

# Create jenkins user
  - name: Add initialization script to setup basic security
    template: 
      src: security.groovy
      dest: '{{ jenkins_home }}/init.groovy.d/security.groovy'
      owner: jenkins
      group: jenkins
      mode: 0775
  
  - name: "Turn off Jenkins setup wizard"
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^JAVA_ARGS='
      line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      insertbefore: '^DAEMON_ARGS='
    notify: Restart Jenkins

  - name: Time for restarting Jenkins
    pause:
      seconds: 60

  - name: Start installing
    jenkins_plugin:
      name: {{ item.name }}
      url_username: '{{ jenkins_user }}'
      url_password: '{{ jenkins_passwd }}'
      url: http://localhost:8080
    loop:
      - {{ name: greenballs }}
      - {{ name: locale }}
      - {{ name: publish-over-ssh }}
      - {{ name: ssh-slaves }}
      - {{ name: cloudbees-folder }}
      - {{ name: antisamy-markup-formatter }}
      - {{ name: build-timeout }}
      - {{ name: credentials-binding }}
      - {{ name: timestamper }}
      - {{ name: ws-cleanup }}
      - {{ name: workflow-aggregator }}
      - {{ name: pipeline-stage-view }}
      - {{ name: pipeline-github-lib }}
      - {{ name: github-branch-source }}
      - {{ name: git }}
      - {{ name: github }}
      - {{ name: pipeline-maven }}
      - {{ name: maven-plugin }}
        
  when: inventory_hostname == "AmazonLinux"