---
# tasks file for jenkins
- block: # Install Jenkins to AmazonLinux1

  - name: Add official Jenkins repo for CentOS
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install Jenkins
    yum: update_cache=yes name=jenkins state=present

  - name: Start and enable Jenkins during boot
    service: name=jenkins state=started enabled=yes

# Create directory if not exists
  - name: Create initialization scripts directory
    file: 
      path: '{{ jenkins_home }}/init.groovy.d'
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0775

# Create jenkins user
  - name: Add initialization script to setup basic security
    template: 
      src: security.groovy.j2
      dest: '{{ jenkins_home }}/init.groovy.d/security.groovy'
      owner: jenkins
      group: jenkins
      mode: 0775
  
  - name: Turn off Jenkins setup wizard
    lineinfile:
      dest: /etc/sysconfig/jenkins
      regexp: '^JAVA_ARGS='
      line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      insertbefore: '^DAEMON_ARGS='
    notify: Restart Jenkins

  - name: Pause for 90 seconds to let Jenkins getting restarted
    pause:
      seconds: 90

  - name: Install Jenkins plugins
    jenkins_plugin:
      name: '{{ item }}'
      url_username: '{{ jenkins_user }}'
      url_password: '{{ jenkins_passwd }}'
      url: http://localhost:8080
    loop:
      - greenballs
      - locale
      - publish-over-ssh
      - ssh-slaves
      - cloudbees-folder
      - antisamy-markup-formatter
      - build-timeout
      - credentials-binding
      - timestamper
      - ws-cleanup
      - workflow-aggregator
      - pipeline-stage-view
      - pipeline-github-lib
      - github-branch-source
      - git
      - github
      - pipeline-maven
      - maven-plugin
      - ssh-agent
      - blueocean
    notify: Restart Jenkins

  when: inventory_hostname == "AmazonLinux"