---
# tasks file for jenkins
- block: # Install Jenkins to AmazonLinux1

  - name: Add official Jenkins repo for CentOS
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: Install Jenkins
    yum: update_cache=yes name=jenkins state=present

  - name: Start and enable Jenkins during boot
    service: name=jenkins state=started enabled=yes

  when: inventory_hostname == "AmazonLinux1"