---
- name: Install Jenkins plugins
  hosts: cicd

  tasks:
    - name: Start installing
      jenkins_plugin:
        name: {{ item }}
        url_username: '{{ jenkins_user }}'
        url_password: '{{ jenkins_passwd }}'
        url: http://localhost:8080
      loop:
        - greenballs
        - locale
        - publish-over-ssh
        - ssh-slaves
        - cloudbees-folder
        - antisamy-markup-formatter
        - build-timeout
        - credentials-binding
        - timestamper
        - ws-cleanup
        - workflow-aggregator
        - pipeline-stage-view
        - pipeline-github-lib
        - github-branch-source
        - git
        - github
        - pipeline-maven
        - maven-plugin


'''
  - name: Install plugin blueocean
    jenkins_plugin:
      name: blueocean
      url_username: '{{ jenkins_user }}'
      url_password: '{{ jenkins_passwd }}'
      url: http://localhost:8080

  - name: Install plugin greenballs
    jenkins_plugin:
      name: blueocean
      url_username: '{{ jenkins_user }}'
      url_password: '{{jenkins_passwd}}'
      url: http://localhost:8080

  when: inventory_hostname == "AmazonLinux"
'''        