---
- name: Install Jenkins plugins
  hosts: cicd

  tasks:
    - name: Start installing
      jenkins_plugin:
        name: {{ item.name }}
        url_username: '{{ jenkins_user }}'
        url_password: '{{ jenkins_passwd }}'
        url: http://localhost:8080
      loop:
        - {{ name: greenballs }}
        - {{ name: locale }}
        - {{ name: publish-over-ssh }}
        - {{ name: ssh-slaves }}
        - {{ name: cloudbees-folder }}
        - {{ name: antisamy-markup-formatter }}
        - {{ name: build-timeout }}
        - {{ name: credentials-binding }}
        - {{ name: timestamper }}
        - {{ name: ws-cleanup }}
        - {{ name: workflow-aggregator }}
        - {{ name: pipeline-stage-view }}
        - {{ name: pipeline-github-lib }}
        - {{ name: github-branch-source }}
        - {{ name: git }}
        - {{ name: github }}
        - {{ name: pipeline-maven }}
        - {{ name: maven-plugin }}


'''
      - name: Install plugin blueocean
    jenkins_plugin:
      name: blueocean
      url_username: '{{ jenkins_user }}'
      url_password: '{{ jenkins_passwd }}'
      url: http://localhost:8080

  - name: Install plugin greenballs
    jenkins_plugin:
      name: blueocean
      url_username: '{{ jenkins_user }}'
      url_password: '{{jenkins_passwd}}'
      url: http://localhost:8080

  when: inventory_hostname == "AmazonLinux"
'''        